/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  home: [
    'index',
    {
      type: 'category',
      label: 'Brands',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'dji/index',
        },
      ],
    },
  ],

  dji: [
    {
      type: 'autogenerated',
      dirName: 'dji',
    }
  ],
};

module.exports = sidebars;
